In [2]:
#a) Create an M X N matrix using numpy arrays. The values of M and N should be taken as input from 
 #the user.
import numpy as np


M = int(input("Enter the number of rows (M): "))
N = int(input("Enter the number of columns (N): "))

matrix = np.random.rand(M, N)

print("Generated M x N matrix:")
print(matrix)



Enter the number of rows (M):  3
Enter the number of columns (N):  3


Generated M x N matrix:
[[0.55054238 0.44654982 0.85014899]
 [0.39238524 0.60034464 0.65482223]
 [0.76462188 0.71961623 0.69235646]]


In [4]:
#b) Perform the operations of Matrix addition and Multiplication using python lists and arrays
#Matrix Addition and Multiplication using Python Lists
#Matrix Addition using Python Lists:
def matrix_addition(A, B):
    
    result = [[0 for _ in range(len(A[0]))] for _ in range(len(A))]

    
    for i in range(len(A)):
        for j in range(len(A[0])):
            result[i][j] = A[i][j] + B[i][j]

    return result


A = [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9]]

B = [[9, 8, 7], 
     [6, 5, 4], 
     [3, 2, 1]]


result_add = matrix_addition(A, B)
print("Matrix Addition Result using Lists:")
for row in result_add:
    print(row)



Matrix Addition Result using Lists:
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [5]:
#Matrix Multiplication using Python Lists:
def matrix_multiplication(A, B):
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]

    
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]

    return result


result_mul = matrix_multiplication(A, B)
print("Matrix Multiplication Result using Lists:")
for row in result_mul:
    print(row)


Matrix Multiplication Result using Lists:
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


In [7]:
#Matrix Addition and Multiplication using NumPy Arrays
#Matrix Addition using NumPy Arrays:
import numpy as np


A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

B = np.array([[9, 8, 7], 
              [6, 5, 4], 
              [3, 2, 1]])


result_add_np = A + B


print("Matrix Addition Result using NumPy Arrays:")
print(result_add_np)


Matrix Addition Result using NumPy Arrays:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [8]:
#Matrix Multiplication using NumPy Arrays:
# Matrix Multiplication
result_mul_np = np.dot(A, B)


print("Matrix Multiplication Result using NumPy Arrays:")
print(result_mul_np)


Matrix Multiplication Result using NumPy Arrays:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [9]:
#c) Using Python coding and also built in Math functions write a program to perform matrix inversion
import numpy as np

def invert_matrix(matrix):
    
    np_matrix = np.array(matrix)
    
    
    try:
        
        inverse_matrix = np.linalg.inv(np_matrix)
        return inverse_matrix
    except np.linalg.LinAlgError:
        raise ValueError("Matrix is singular and cannot be inverted")


matrix = [
    [4, 7],
    [2, 6]
]

inverted_matrix = invert_matrix(matrix)
print("Inverted Matrix:")
print(inverted_matrix)


Inverted Matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]
