In [14]:
#a)Writng and reading matrix
import numpy as np


rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))


matrix1 = []
matrix2 = []


print("\nEnter the elements of the first matrix:")
for i in range(rows):
    row = []
    for j in range(cols):
        element = int(input(f"Enter element for row {i+1}, column {j+1}: "))
        row.append(element)
    matrix1.append(row)


matrix1 = np.array(matrix1)


print("\nEnter the elements of the second matrix:")
for i in range(rows):
    row = []
    for j in range(cols):
        element = int(input(f"Enter element for row {i+1}, column {j+1}: "))
        row.append(element)
    matrix2.append(row)


matrix2 = np.array(matrix2)

# Print the matrices
print("\nFirst Matrix:")
print(matrix1)

print("\nSecond Matrix:")
print(matrix2)



Enter the number of rows:  3
Enter the number of columns:  2



Enter the elements of the first matrix:


Enter element for row 1, column 1:  3
Enter element for row 1, column 2:  4
Enter element for row 2, column 1:  2
Enter element for row 2, column 2:  4
Enter element for row 3, column 1:  5
Enter element for row 3, column 2:  2



Enter the elements of the second matrix:


Enter element for row 1, column 1:  3
Enter element for row 1, column 2:  4
Enter element for row 2, column 1:  5
Enter element for row 2, column 2:  6
Enter element for row 3, column 1:  7
Enter element for row 3, column 2:  8



First Matrix:
[[3 4]
 [2 4]
 [5 2]]

Second Matrix:
[[3 4]
 [5 6]
 [7 8]]


In [15]:
#B)Matrix Addition and Multiplication of given dimensions
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

if matrix1.shape != matrix2.shape:
    print("Error: The matrices must have the same dimensions for addition.")
else:
    matrix_sum = matrix1 + matrix2

    print("Matrix 1:")
    print(matrix1)
    print("\nMatrix 2:")
    print(matrix2)
    print("\nSum of Matrices:")
    print(matrix_sum)

if matrix1.shape[1] != matrix2.shape[0]:
    print("Error: The number of columns in the first matrix must equal the number of rows in the second matrix for multiplication.")
else:
    matrix_product = np.dot(matrix1, matrix2)

    print("\nProduct of Matrices:")
    print(matrix_product)



Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Sum of Matrices:
[[ 6  8]
 [10 12]]

Product of Matrices:
[[19 22]
 [43 50]]


In [12]:
#c) Matrix Transpose and Matrix Inversion.
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6]])

transpose_matrix = matrix.T

transpose_matrix_alt = np.transpose(matrix)

print("Original Matrix:")
print(matrix)
print("\nTransposed Matrix (using .T):")
print(transpose_matrix)
print("\nTransposed Matrix (using np.transpose()):")
print(transpose_matrix_alt)


Original Matrix:
[[1 2 3]
 [4 5 6]]

Transposed Matrix (using .T):
[[1 4]
 [2 5]
 [3 6]]

Transposed Matrix (using np.transpose()):
[[1 4]
 [2 5]
 [3 6]]


In [13]:
#inverse
import numpy as np


matrix = np.array([[1, 2], [3, 4]])

#findingg inverse using numpy.linalg.inv()
inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix:")
print(matrix)
print("\nInverse Matrix:")
print(inverse_matrix)

Original Matrix:
[[1 2]
 [3 4]]

Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]
